#! /bin/sh

sxhkd &

dunst &

feh --bg-scale /home/milosh/.config/bspwm/wallpapers/wp2.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
